# Build the website - queries Bintray and OJO APIs for latest version information
script:
  - mkdir ./build
  - cp index.html ./build/
  - cp README.md ./build/

# Deploy the website - Travis does not invoke this step for pull request builds
deploy:
  provider: pages # Deploy the current directory to the master branch of the repo
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./build/
  on:
    branch: master